In [421]:
import pandas as pd
import numpy as np

In [422]:
data = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv') #data set

In [423]:
data.head(5) #sample of dataset

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [424]:
data.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [425]:
#Data Pre-Processing
data.isnull().sum() #is na  isnull 0

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [426]:
data = data.dropna()

In [427]:
data.isna().sum() #this dataset has no null values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [428]:
#import libraries
from sklearn.preprocessing  import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [429]:
data.shape

(7043, 21)

In [430]:
print(data.dtypes)

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [431]:
#convertion in label encoder
label_encoder = LabelEncoder()
data['Churn'] = label_encoder.fit_transform(data['Churn'])

data.fillna(0, inplace=True)

In [432]:
data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [433]:
data = pd.get_dummies(data, columns=['gender', 'Partner', 'Dependents', 'PhoneService',
                                     'MultipleLines', 'InternetService', 'OnlineSecurity',
                                     'OnlineBackup', 'DeviceProtection', 'TechSupport',
                                     'StreamingTV', 'StreamingMovies', 'Contract',
                                     'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [434]:
data.head(5)

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,1,29.85,29.85,0,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
1,5575-GNVDE,0,34,56.95,1889.5,0,True,False,False,True,...,False,False,False,False,True,False,False,False,False,True
2,3668-QPYBK,0,2,53.85,108.15,1,True,False,False,True,...,False,False,False,False,False,False,True,False,False,True
3,7795-CFOCW,0,45,42.30,1840.75,0,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,9237-HQITU,0,2,70.70,151.65,1,False,False,False,True,...,False,False,False,False,False,False,True,False,True,False

In [435]:
# Convert boolean columns to integers
data = data.apply(lambda x: x.astype(int) if x.dtype == 'bool' else x)

data.head(5)

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,1,29.85,29.85,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
1,5575-GNVDE,0,34,56.95,1889.5,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,1
2,3668-QPYBK,0,2,53.85,108.15,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,1
3,7795-CFOCW,0,45,42.30,1840.75,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,9237-HQITU,0,2,70.70,151.65,1,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0

In [436]:
print(data.dtypes)

customerID                                object
SeniorCitizen                              int64
tenure                                     int64
MonthlyCharges                           float64
TotalCharges                              object
Churn                                      int64
gender_Male                                int64
Partner_Yes                                int64
Dependents_Yes                             int64
PhoneService_Yes                           int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_One year                          int64
Contract_Two year                          int64
PaperlessBilling_Yes                       int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
dtype: object

In [437]:
# Convert 'TotalCharges' to numeric and handle errors
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

data.fillna(0, inplace=True)

In [438]:
#Y = data['Churn']
data = data.drop(columns=['customerID'],axis=1)
Y = data['Churn']

In [439]:
#Splitting X AND Y (Independent,Dependent features)

X = data.drop(columns=['Churn'],axis=1)
Y = data['Churn']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=43,test_size=0.2)

In [440]:
data.isna().sum()

SeniorCitizen                            0
tenure                                   0
MonthlyCharges                           0
TotalCharges                             0
Churn                                    0
gender_Male                              0
Partner_Yes                              0
Dependents_Yes                           0
PhoneService_Yes                         0
MultipleLines_No phone service           0
MultipleLines_Yes                        0
InternetService_Fiber optic              0
InternetService_No                       0
OnlineSecurity_No internet service       0
OnlineSecurity_Yes                       0
OnlineBackup_No internet service         0
OnlineBackup_Yes                         0
DeviceProtection_No internet service     0
DeviceProtection_Yes                     0
TechSupport_No internet service          0
TechSupport_Yes                          0
StreamingTV_No internet service          0
StreamingTV_Yes                          0
StreamingMovies_No internet service      0
StreamingMovies_Yes                      0
Contract_One year                        0
Contract_Two year                        0
PaperlessBilling_Yes                     0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64

In [441]:
X.dtypes

SeniorCitizen                              int64
tenure                                     int64
MonthlyCharges                           float64
TotalCharges                             float64
gender_Male                                int64
Partner_Yes                                int64
Dependents_Yes                             int64
PhoneService_Yes                           int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_One year                          int64
Contract_Two year                          int64
PaperlessBilling_Yes                       int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
dtype: object

In [442]:
#import standard scaler
from sklearn.preprocessing import StandardScaler

In [443]:
#transform all values into a standard format using standard scaler class object
sc_scaler = StandardScaler()
X_train = sc_scaler.fit_transform(X_train)
X_test = sc_scaler.fit_transform(X_test)

In [444]:
X_train

array([[ 2.27098592, -1.07982514,  0.49495309, ..., -0.51857393,
         1.40522483, -0.54548944],
       [-0.44033738,  0.87653007,  0.74130944, ..., -0.51857393,
        -0.7116299 , -0.54548944],
       [-0.44033738, -0.95755294, -1.00315982, ...,  1.92836536,
        -0.7116299 , -0.54548944],
       ...,
       [-0.44033738, -1.24285474, -0.5670425 , ..., -0.51857393,
         1.40522483, -0.54548944],
       [-0.44033738,  1.03955967, -0.69022068, ..., -0.51857393,
        -0.7116299 ,  1.83321606],
       [-0.44033738, -0.06089014,  0.83452535, ..., -0.51857393,
         1.40522483, -0.54548944]])

In [445]:
X_test

array([[-0.4382321 ,  1.34411809,  0.86417467, ..., -0.55083823,
         1.41120779, -0.54207709],
       [-0.4382321 , -0.07629899,  1.38421979, ..., -0.55083823,
        -0.70861287, -0.54207709],
       [-0.4382321 , -0.07629899,  0.14766805, ...,  1.81541502,
        -0.70861287, -0.54207709],
       ...,
       [-0.4382321 ,  0.04545104, -0.1181328 , ..., -0.55083823,
        -0.70861287,  1.84475608],
       [-0.4382321 , -1.17204932,  0.70073191, ...,  1.81541502,
        -0.70861287, -0.54207709],
       [-0.4382321 ,  1.58761816,  0.48280824, ...,  1.81541502,
        -0.70861287, -0.54207709]])

In [446]:
(X_train.shape[1],1)
(X_train.shape[1],)

(30,)

In [447]:
#build Model using ANN
#Create Model 
model = Sequential()

#Add First layer input
model.add(Dense(128,activation='relu',input_shape=((X_train.shape[1],))))
model.add(Dropout(0.3))

#add Second layer 
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.3))

#add Third layer 
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.3))

#output layer 
model.add(Dense(1, activation='sigmoid'))


#model compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [448]:
#Train the model

early_stop = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

history = model.fit(X_train,Y_train,  epochs=50, batch_size=64, validation_split=0.2, callbacks=[early_stop])

Epoch 1/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7231 - loss: 0.5506 - val_accuracy: 0.7986 - val_loss: 0.4310
Epoch 2/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7800 - loss: 0.4551 - val_accuracy: 0.7959 - val_loss: 0.4242
Epoch 3/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.7749 - loss: 0.4475 - val_accuracy: 0.7933 - val_loss: 0.4235
Epoch 4/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7828 - loss: 0.4427 - val_accuracy: 0.7941 - val_loss: 0.4212
Epoch 5/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8002 - loss: 0.4332 - val_accuracy: 0.8021 - val_loss: 0.4207
Epoch 6/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8066 - loss: 0.4226 - val_accuracy: 0.7977 - val_loss: 0.4185
Epoch 7/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.8116 - loss: 0.4153 - val_accuracy: 0.7977 - val_loss: 0.4219
Epoch 8/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8005 - loss: 0.4235 - val_accuracy: 0.7959 - val_loss: 0.4217
Epoch 9/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.8017 - loss: 0.4219 - val_accuracy: 0.7986 - val_loss: 0.4199
Epoch 10/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.7921 - loss: 0.4279 - val_accuracy: 0.7986 - val_loss: 0.4218
Epoch 11/50
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.8071 - loss: 0.4222 - val_accuracy: 0.7968 - val_loss: 0.4199

In [449]:
# Check for NaN values
print(data.isnull().sum().sum())

0

In [450]:
null_columns = data.columns[data.isna().any()]
print(null_columns)

Index([], dtype='object')

In [451]:
# Evaluate the mode
loss,accuracy= model.evaluate(X_test,Y_test)
print(f'model accuract',accuracy)

45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 0.8126 - loss: 0.4044
model accuract 0.8090844750404358

In [452]:
# save the mode using jolib 
import joblib
joblib.dump(model,'churn_model.pkl')

['churn_model.pkl']

In [453]:
#save standard scaler
joblib.dump(sc_scaler,'sc_scaler.pkl')

['sc_scaler.pkl']

In [497]:
# Save the column names after get_dummies()
feature_columns = data.columns.to_list()


# Save feature columns after get_dummies()
feature_columns = data.columns.to_list()
joblib.dump(feature_columns, 'feature_columns.pkl')
print("Feature columns saved successfully!")

Feature columns saved successfully!

In [455]:
len(data.columns)

31

In [495]:
data.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')