In [1]:
#load the model load the gender and geography pickel files
import pickle

In [5]:
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import tensorflow as tf

In [9]:
model = load_model('model.keras')

#load label encode
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

#load onehot encode for geography
with open('one_hot_encoder_geography.pkl','rb') as file:
    one_hot_encoder_geo = pickle.load(file)

In [37]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [39]:
label_encoder_gender

LabelEncoder()

In [40]:
#transform geo
geo_encoder = one_hot_encoder_geo.   transform([[input_data['Geography']]]).toarray()
#geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
df_geo = pd.DataFrame(geo_encoder, columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
         #pd.DataFrame(geo_encoded, columns=label_encoder_geo. get_feature_names_out(['Geography']))
df_geo

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [42]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [43]:
#data frame for gender
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])

In [44]:
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [ ]:
#drop gegraphy
input_df.drop(columns=['Geography'],axis=1)

   CreditScore  Age  Tenure  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600   40       3  ...          1               1            50000

[1 rows x 8 columns]

In [46]:
input_df = pd.concat([input_df,df_geo],axis=1)

In [67]:
input_df = input_df.drop(columns=['Geography'],axis=1)

In [62]:
#scale the input
#import scaler pkl file
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [69]:
input_df
input_scaled = scaler.transform(input_df)

In [70]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [71]:
predection = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

In [72]:
predection

array([[0.01082566]], dtype=float32)

In [73]:
churn_value = predection[0][0]

In [74]:
churn_value

0.010825662

In [75]:
if churn_value > 0.5:
    print("customer likely to churn")
else:
    print("Customer will stay")

Customer will stay